# Generated by Django 5.2.8 on 2025-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'زنانه'), ('men', 'مردانه'), ('unisex', 'یونیسکس')], default='unisex', max_length=20),
        ),
    ]
